# generated by datamodel-codegen:
#   filename:  openapi.yml
#   timestamp: 2026-03-28T15:49:07+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    SecretStr,
)


class ErrorCode(Enum):
    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    DSL_PARSE_ERROR = "DSL_PARSE_ERROR"
    DSL_INVALID_FIELD = "DSL_INVALID_FIELD"
    DSL_INVALID_OPERATOR = "DSL_INVALID_OPERATOR"
    RULE_NAME_ALREADY_EXISTS = "RULE_NAME_ALREADY_EXISTS"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class ApiError(BaseModel):
    code: ErrorCode
    message: Annotated[
        str,
        Field(
            description="Human-readable message (for display to user)",
            examples=["Bad request"],
        ),
    ]
    traceId: Annotated[
        UUID,
        Field(
            description="Unique request identifier for tracing.\nUsed for searching in logs during debugging.\n",
            examples=["[UUID73]"],
        ),
    ]
    timestamp: Annotated[
        AwareDatetime, Field(description="Error occurrence time (ISO 8601, UTC)")
    ]
    path: Annotated[
        str,
        Field(
            description="Request path where error occurred",
            examples=["/api/v1/transactions"],
        ),
    ]
    details: Annotated[
        dict[str, Any] | None, Field(description="Additional error details")
    ] = None


class FieldError(BaseModel):
    field: Annotated[
        str,
        Field(
            description='Field name with error (can be nested, e.g. "location.latitude")',
            examples=["amount"],
        ),
    ]
    issue: Annotated[
        str, Field(description="Problem description", examples=["must be >= 0.01"])
    ]
    rejectedValue: Annotated[
        Any | None, Field(description="Value that failed validation")
    ] = None


class UserRole(Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class Gender(Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"


class MaritalStatus(Enum):
    SINGLE = "SINGLE"
    MARRIED = "MARRIED"
    DIVORCED = "DIVORCED"
    WIDOWED = "WIDOWED"


class TransactionStatus(Enum):
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"


class TransactionChannel(Enum):
    WEB = "WEB"
    MOBILE = "MOBILE"
    POS = "POS"
    OTHER = "OTHER"


class CurrencyCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="ISO 4217 currency code", examples=["RUB"], pattern="^[A-Z]{3}$"
        ),
    ]


class MccCode(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Merchant Category Code (4 digits)",
            examples=["5411"],
            pattern="^\\d{4}$",
        ),
    ]


class RegisterRequest(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    email: Annotated[EmailStr, Field(description="User email (unique)", max_length=254)]
    password: Annotated[
        SecretStr,
        Field(
            description="Password. Requirements:\n- Minimum 8 characters\n- Minimum 1 letter (A-Z or a-z)\n- Minimum 1 digit (0-9)\n",
            max_length=72,
            min_length=8,
            pattern="^(?=.*[A-Za-z])(?=.*\\d).+$",
        ),
    ]
    fullName: Annotated[
        str,
        Field(
            description="User full name",
            examples=["Ivan Ivanov"],
            max_length=200,
            min_length=2,
        ),
    ]
    region: Annotated[
        str | None,
        Field(
            description="User region (region code or arbitrary string)",
            examples=["RU-MOW"],
            max_length=32,
        ),
    ] = None
    gender: Gender | None = None
    age: Annotated[
        int | None,
        Field(description="Age (minimum 18 years)", examples=[25], ge=18, le=120),
    ] = None
    maritalStatus: MaritalStatus | None = None


class LoginRequest(BaseModel):
    email: Annotated[EmailStr, Field(max_length=254)]
    password: Annotated[SecretStr, Field(max_length=72, min_length=8)]


class User(BaseModel):
    id: UUID
    email: Annotated[EmailStr, Field(max_length=254)]
    fullName: Annotated[str, Field(max_length=200, min_length=2)]
    region: Annotated[
        str | None, Field(description="Residence region", max_length=32)
    ] = None
    gender: Gender | None = None
    age: Annotated[int | None, Field(ge=18, le=120)] = None
    maritalStatus: MaritalStatus | None = None
    role: UserRole
    isActive: Annotated[
        bool,
        Field(description="Whether user is active (deactivated users cannot log in)"),
    ]
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class UserCreateRequest(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    email: Annotated[EmailStr, Field(max_length=254)]
    password: Annotated[
        SecretStr,
        Field(max_length=72, min_length=8, pattern="^(?=.*[A-Za-z])(?=.*\\d).+$"),
    ]
    fullName: Annotated[str, Field(max_length=200, min_length=2)]
    region: Annotated[str | None, Field(max_length=32)] = None
    gender: Gender | None = None
    age: Annotated[int | None, Field(ge=18, le=120)] = None
    maritalStatus: MaritalStatus | None = None
    role: UserRole


class UserUpdateRequest(BaseModel):
    fullName: Annotated[str, Field(max_length=200, min_length=2)]
    region: Annotated[str, Field(max_length=32)]
    gender: Gender
    age: Annotated[int, Field(ge=18, le=120)]
    maritalStatus: MaritalStatus
    role: Annotated[
        UserRole | None,
        Field(description="Only ADMIN can change role. USER will get 403 on attempt."),
    ] = None
    isActive: Annotated[
        bool | None, Field(description="Only ADMIN can change isActive.")
    ] = None


class PagedUsers(BaseModel):
    items: list[User]
    total: Annotated[int, Field(description="Total number of records", ge=0)]
    page: Annotated[int, Field(description="Current page (0-based)", ge=0)]
    size: Annotated[int, Field(description="Page size", ge=1)]


class TransactionLocation(BaseModel):
    country: Annotated[
        str | None,
        Field(
            description="ISO 3166-1 alpha-2 country code (uppercase letters)",
            examples=["RU"],
            max_length=2,
            min_length=2,
            pattern="^[A-Z]{2}$",
        ),
    ] = None
    city: Annotated[
        str | None, Field(description="City name", examples=["Moscow"], max_length=128)
    ] = None
    latitude: Annotated[
        float | None,
        Field(
            description="Latitude (requires longitude)",
            examples=[55.7558],
            ge=-90.0,
            le=90.0,
        ),
    ] = None
    longitude: Annotated[
        float | None,
        Field(
            description="Longitude (requires latitude)",
            examples=[37.6173],
            ge=-180.0,
            le=180.0,
        ),
    ] = None


class Transaction(BaseModel):
    id: UUID
    userId: UUID
    amount: Annotated[
        float,
        Field(
            description="Transaction amount",
            examples=[1999.99],
            ge=0.01,
            le=999999999.99,
        ),
    ]
    currency: CurrencyCode
    status: TransactionStatus
    merchantId: Annotated[
        str | None,
        Field(description="Merchant identifier", examples=["shop-123"], max_length=64),
    ] = None
    merchantCategoryCode: MccCode | None = None
    timestamp: Annotated[
        AwareDatetime, Field(description="Operation time (specified by client)")
    ]
    ipAddress: Annotated[
        str | None,
        Field(description="Client IP address", examples=["192.168.0.1"], max_length=64),
    ] = None
    deviceId: Annotated[
        str | None,
        Field(description="Device identifier", examples=["device-abc"], max_length=128),
    ] = None
    channel: TransactionChannel | None = None
    location: TransactionLocation | None = None
    isFraud: Annotated[
        bool,
        Field(
            description="Flag indicating transaction is marked as fraud (at least one rule triggered)"
        ),
    ]
    metadata: Annotated[
        dict[str, Any] | None, Field(description="Arbitrary additional data")
    ] = None
    createdAt: Annotated[
        AwareDatetime, Field(description="Record creation time in the system")
    ]


class TransactionCreateRequest(BaseModel):
    userId: Annotated[
        UUID,
        Field(
            description="ID of user for whom transaction is created.\nUSER can create only for themselves (userId == id from token).\nADMIN can create for any user.\n"
        ),
    ]
    amount: Annotated[float, Field(ge=0.01, le=999999999.99)]
    currency: CurrencyCode
    merchantId: Annotated[str | None, Field(max_length=64)] = None
    merchantCategoryCode: MccCode | None = None
    timestamp: Annotated[
        AwareDatetime,
        Field(
            description="Operation time. Must not be too far in the future (> now + 5 minutes => 422).\n"
        ),
    ]
    ipAddress: Annotated[str | None, Field(max_length=64)] = None
    deviceId: Annotated[str | None, Field(max_length=128)] = None
    channel: TransactionChannel | None = None
    location: TransactionLocation | None = None
    metadata: dict[str, Any] | None = None


class TransactionBatchCreateRequest(BaseModel):
    items: Annotated[
        list[TransactionCreateRequest],
        Field(
            description="Array of transactions for batch creation",
            max_length=500,
            min_length=1,
        ),
    ]


class FraudRuleEvaluationResult(BaseModel):
    ruleId: UUID
    ruleName: str
    priority: Annotated[int, Field(ge=1)]
    enabled: bool
    matched: Annotated[
        bool, Field(description="true if rule triggered (condition met)")
    ]
    description: Annotated[
        str | None, Field(description="Human-readable description of check result")
    ] = None


class TransactionDecision(BaseModel):
    transaction: Transaction
    ruleResults: Annotated[
        list[FraudRuleEvaluationResult],
        Field(
            description="Results of applying all enabled rules at the time of check.\nAll rules are returned (both triggered and not triggered).\n"
        ),
    ]


class PagedTransactions(BaseModel):
    items: list[Transaction]
    total: Annotated[int, Field(ge=0)]
    page: Annotated[int, Field(ge=0)]
    size: Annotated[int, Field(ge=1)]


class TransactionBatchResultItem(BaseModel):
    index: Annotated[
        int, Field(description="Element index in original array (0-based)", ge=0)
    ]
    decision: Annotated[
        TransactionDecision | None,
        Field(description="Result if transaction successfully processed"),
    ] = None
    error: Annotated[
        ApiError | None,
        Field(
            description="Error if element not processed (validation/access/conflict)"
        ),
    ] = None


class TransactionBatchResult(BaseModel):
    items: list[TransactionBatchResultItem]


class FraudRule(BaseModel):
    id: UUID
    name: Annotated[
        str, Field(description="Unique rule name", max_length=120, min_length=3)
    ]
    description: Annotated[
        str | None,
        Field(description="Rule description (for documentation)", max_length=500),
    ] = None
    dslExpression: Annotated[
        str,
        Field(
            description="DSL expression of the rule. Supported syntax:\n\nTransaction fields: amount, currency, merchantId, ipAddress, deviceId\nUser fields: user.age, user.region\n\nComparison operators: >, >=, <, <=, =, !=\nLogical operators: AND, OR, NOT\nParentheses for grouping: ()\n\nExamples:\n- amount > 10000\n- amount > 5000 AND currency = 'RUB'\n- user.age < 21 AND amount > 10000\n- (amount > 10000 OR user.region = 'HIGH_RISK') AND NOT (currency = 'USD')\n",
            max_length=2000,
            min_length=3,
        ),
    ]
    enabled: Annotated[
        bool,
        Field(description="Whether rule is active (inactive rules are not applied)"),
    ]
    priority: Annotated[
        int,
        Field(
            description="Priority (lower number = higher priority, checked earlier)",
            ge=1,
        ),
    ]
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class FraudRuleCreateRequest(BaseModel):
    name: Annotated[str, Field(max_length=120, min_length=3)]
    description: Annotated[str | None, Field(max_length=500)] = None
    dslExpression: Annotated[str, Field(max_length=2000, min_length=3)]
    enabled: bool | None = True
    priority: Annotated[int | None, Field(ge=1)] = 100


class FraudRuleUpdateRequest(BaseModel):
    name: Annotated[str, Field(max_length=120, min_length=3)]
    description: Annotated[str | None, Field(max_length=500)] = None
    dslExpression: Annotated[str, Field(max_length=2000, min_length=3)]
    enabled: bool
    priority: Annotated[int, Field(ge=1)]


class DslValidateRequest(BaseModel):
    dslExpression: Annotated[str, Field(max_length=2000, min_length=3)]


class DslError(BaseModel):
    code: Annotated[str, Field(examples=["DSL_PARSE_ERROR"])]
    message: str
    position: Annotated[
        int | None, Field(description="Error position in expression (0-based)")
    ] = None
    near: Annotated[
        str | None, Field(description="Expression fragment near the error")
    ] = None


class MerchantRiskRow(BaseModel):
    merchantId: str
    merchantCategoryCode: MccCode | None = None
    txCount: Annotated[int, Field(description="Number of transactions", ge=0)]
    gmv: Annotated[float | None, Field(ge=0.0)] = None
    declineRate: Annotated[
        float, Field(description="Share of declined transactions", ge=0.0, le=1.0)
    ]


class TransactionsTimePoint(BaseModel):
    bucketStart: Annotated[
        AwareDatetime, Field(description="Time interval (bucket) start")
    ]
    txCount: Annotated[
        int, Field(description="Number of transactions in interval", ge=0)
    ]
    gmv: Annotated[float, Field(description="Sum of transactions in interval", ge=0.0)]
    approvalRate: Annotated[
        float,
        Field(description="Share of APPROVED transactions (0..1)", ge=0.0, le=1.0),
    ]
    declineRate: Annotated[
        float,
        Field(description="Share of DECLINED transactions (0..1)", ge=0.0, le=1.0),
    ]


class RuleMatchRow(BaseModel):
    ruleId: UUID
    ruleName: str
    matches: Annotated[int, Field(description="Number of rule triggers", ge=0)]
    uniqueUsers: Annotated[
        int, Field(description="Unique users affected by rule", ge=0)
    ]
    uniqueMerchants: Annotated[
        int | None, Field(description="Unique merchants affected by rule", ge=0)
    ] = None
    shareOfDeclines: Annotated[
        float,
        Field(
            description="Share of DECLINED transactions where this rule was among matched",
            ge=0.0,
            le=1.0,
        ),
    ]


class MerchantRiskStats(BaseModel):
    items: list[MerchantRiskRow]


class UserRiskProfile(BaseModel):
    userId: UUID
    txCount_24h: Annotated[
        int, Field(description="Number of transactions in last 24 hours", ge=0)
    ]
    gmv_24h: Annotated[
        float, Field(description="Sum of transactions in last 24 hours", ge=0.0)
    ]
    distinctDevices_24h: Annotated[
        int, Field(description="Unique devices in last 24 hours", ge=0)
    ]
    distinctIps_24h: Annotated[
        int, Field(description="Unique IP addresses in last 24 hours", ge=0)
    ]
    distinctCities_24h: Annotated[
        int, Field(description="Unique cities in last 24 hours", ge=0)
    ]
    declineRate_30d: Annotated[
        float,
        Field(
            description="Share of declined transactions in last 30 days", ge=0.0, le=1.0
        ),
    ]
    lastSeenAt: Annotated[
        AwareDatetime | None, Field(description="Last activity time")
    ] = None


class ValidationError(BaseModel):
    code: Annotated[str, Field(examples=["VALIDATION_FAILED"])]
    message: str
    traceId: UUID
    timestamp: AwareDatetime
    path: str
    fieldErrors: list[FieldError]


class AuthResponse(BaseModel):
    accessToken: Annotated[
        str,
        Field(
            description="JWT token for request authorization.\nPass in header: Authorization: Bearer <token>\n",
            examples=["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."],
        ),
    ]
    expiresIn: Annotated[
        int,
        Field(
            description="Token lifetime in seconds.\nAfter expiration, token becomes invalid and a new one must be obtained via /auth/login.\n",
            examples=[3600],
            ge=1,
        ),
    ]
    user: User


class DslValidateResponse(BaseModel):
    isValid: bool
    normalizedExpression: Annotated[
        str | None, Field(description="Normalized expression (if valid)")
    ] = None
    errors: list[DslError]


class StatsOverview(BaseModel):
    from_: Annotated[
        AwareDatetime, Field(alias="from", description="Period start (inclusive)")
    ]
    to: Annotated[AwareDatetime, Field(description="Period end (exclusive)")]
    volume: Annotated[
        int, Field(description="Total number of transactions for the period", ge=0)
    ]
    gmv: Annotated[
        float,
        Field(
            description="Gross Merchandise Value — sum of amount of all transactions.\nIncludes both APPROVED and DECLINED transactions.\n",
            ge=0.0,
        ),
    ]
    approvalRate: Annotated[
        float,
        Field(
            description="Share of APPROVED transactions (0..1).\napprovalRate + declineRate = 1\n",
            ge=0.0,
            le=1.0,
        ),
    ]
    declineRate: Annotated[
        float,
        Field(
            description="Share of DECLINED transactions (0..1).\nEquivalent to share of transactions with isFraud=true.\n",
            ge=0.0,
            le=1.0,
        ),
    ]
    topRiskMerchants: Annotated[
        list[MerchantRiskRow],
        Field(description="Top 10 merchants with highest declineRate"),
    ]


class TransactionsTimeSeries(BaseModel):
    points: list[TransactionsTimePoint]


class RuleMatchStats(BaseModel):
    items: list[RuleMatchRow]
