from dataclasses import dataclass
from datetime import datetime
from typing import Protocol
from uuid import UUID

from prodik.domain.fraud import FraudRule
from prodik.domain.transaction import RuleResults, Transaction, TransactionStatus
from prodik.domain.user import User, UserCredentials


@dataclass(slots=True, frozen=True, kw_only=True)
class TransactionFilters:
    target_id: UUID | None
    status: TransactionStatus | None
    is_fraud: bool | None
    from_date: datetime | None
    to_date: datetime | None
    page: int
    size: int


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_id(self, target_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_users_by_offset(self, page: int, size: int) -> list[User]: ...


class RuleResultsRepostiory(Protocol):
    async def create(self, rule_result: RuleResults) -> None: ...
    async def create_many(self, rule_results: list[RuleResults]) -> None: ...
    async def get_all_by_transaction_id(self, target_id: UUID) -> list[RuleResults]: ...


class TransactionRepository(Protocol):
    async def create(self, transaction: Transaction) -> None: ...
    async def create_many(self, transactions: list[Transaction]) -> None: ...
    async def get_by_id(self, target_id: UUID) -> Transaction | None: ...
    async def get_all_by_filters(self, filters: TransactionFilters) -> list[Transaction]: ...


class UserCredentialsRepository(Protocol):
    async def create(self, credentials: UserCredentials) -> None: ...
    async def get_by_user_id(self, target_id: UUID) -> UserCredentials | None: ...


class FraudRuleRepository(Protocol):
    async def get_all_rules(self) -> list[FraudRule]: ...
    async def create(self, fraud_rule: FraudRule) -> None: ...
    async def update(self, fraud_rule: FraudRule) -> None: ...
    async def get_all_sorted_by_priority(self) -> list[FraudRule]: ...
    async def get_by_id(self, target_id: UUID) -> FraudRule | None: ...
    async def get_by_name(self, fraud_rule_name: str) -> FraudRule | None: ...
