from typing import Protocol
from uuid import UUID

from prodik.domain.fraud import FraudRule
from prodik.domain.user import User, UserCredentials


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_id(self, target_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_users_by_offset(self, page: int, size: int) -> list[User]: ...


class UserCredentialsRepository(Protocol):
    async def create(self, credentials: UserCredentials) -> None: ...
    async def get_by_user_id(self, user_id: UUID) -> UserCredentials | None: ...


class FraudRuleRepository(Protocol):
    async def create(self, fraud_rule: FraudRule) -> None: ...
    async def update(self, fraud_rule: FraudRule) -> None: ...
    async def get_by_name(self, fraud_rule_name: str) -> FraudRule | None: ...
    async def get_by_id(self, target_id: UUID) -> FraudRule | None: ...
    async def get_all_rules(self) -> list[FraudRule]: ...
