class ApplicationError(Exception):
    def __init__(self, detail: str) -> None:
        self.detail = detail
        super().__init__(detail)


class UserAlreadyExistsError(ApplicationError): ...


class NotEnoughRightsError(ApplicationError): ...

class UserDeactivatedError(ApplicationError): ...

class WrongCredentialsError(ApplicationError): ...


class UserNotFoundError(ApplicationError): ...


class InvalidTokenFormatError(ApplicationError): ...


class IncorrectTokenTypeError(ApplicationError): ...


class TokenNotFoundError(ApplicationError): ...
