from typing import Protocol
from uuid import UUID

from prodik.domain.user import User, UserCredentials


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_id(self, uuid: UUID) -> User: ...
    async def get_by_email(self, email: str) -> User: ...
    async def find_by_id(self, uuid: UUID) -> User | None: ...

class UserCredentialsRepository(Protocol):
    async def create(self, credentials: UserCredentials) -> None: ...
