from typing import Protocol
from uuid import UUID

from prodik.domain.user import User, UserCredentials


class UserRepository(Protocol):
    async def create(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def get_by_id(self, uuid: UUID) -> User: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_users_by_offset(self, page: int, size: int) -> list[User]: ...


class UserCredentialsRepository(Protocol):
    async def create(self, credentials: UserCredentials) -> None: ...
    async def get_by_user_id(self, uuid: UUID) -> UserCredentials | None: ...
